services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - 5432:${DB_PORT}
    restart: always
    network_mode: "host"

  app:
    build:
      context: ./web
      target: dev
    tty: true
    working_dir: /opt/server
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

    volumes:
      - ./web:/opt/server
      - ./static:/opt/static
    env_file:
      - ./.env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_started
    container_name: "bun"
    network_mode: "host"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /opt/server/web/src
        - action: rebuild
          path: package.json
          target: /opt/server/web

  nginx:
    container_name: nginx
    depends_on:
      - app
      - db
      # - pgadmin
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always
    network_mode: "host"

volumes:
  postgres_data:
