services:
  app:
    build:
      context: ./web
      target: dev
    tty: true
    working_dir: /opt/server
    volumes:
      - ./web:/opt/server
      - ./static:/opt/static
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /opt/server/web/src

        - action: rebuild
          path: package.json
          target: /opt/server/web

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - 5432:5432
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: german.makarkin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
    expose:
      - "80"
    restart: always
